var mongoose = require("mongoose");
var Schema = mongoose.Schema;

var img_schema = new Schema({
	title:{type:String,require:true},
	creator:{type:Schema.Types.ObjectId, ref: "User" },
	extension:{type:String,require:true},
	extension1:{type:String,require:true},
	extension2:{type:String,require:true},
	extension3:{type:String,require:true},
	extension4:{type:String,require:true},
	foto:{type:String,require:true},
	nombre1:{type:String,require:true},
	uso:{type:String,require:true},
	Localidad:{type:String,require:true},
	dlugar:{type:String,require:true},
	precio:{type:String,require:true},
	preriodo:{type:String,require:true},
	precio1:{type:String,require:true},
	preriodo1:{type:String,require:true},
	precio2:{type:String,require:true},
	preriodo2:{type:String,require:true},
	precio3:{type:String,require:true},
	preriodo3:{type:String,require:true},
	radio1:{type:String,require:true},
	radio2:{type:String,require:true},
	radio3:{type:String,require:true},
	radio4:{type:String,require:true},
	radio5:{type:String,require:true},
	radio6:{type:String,require:true},
	radio7:{type:String,require:true},
	radio8:{type:String,require:true},
	radio9:{type:String,require:true},
	radio10:{type:String,require:true},
	radio11:{type:String,require:true},
	radio12:{type:String,require:true},
	radio13:{type:String,require:true},
	radio14:{type:String,require:true},
	radio15:{type:String,require:true},
	radio16:{type:String,require:true},
	radio17:{type:String,require:true},
	radio18:{type:String,require:true},
	radio19:{type:String,require:true},
	radio20:{type:String,require:true},
	radio21:{type:String,require:true},
	radio22:{type:String,require:true},
	radio23:{type:String,require:true},
	radio24:{type:String,require:true},
	radio25:{type:String,require:true},
	radio26:{type:String,require:true},
	radio27:{type:String,require:true},
	tipo:{type:String,require:true},
	dir:{type:String,require:true},
});

var Imagen = mongoose.model("Imagen",img_schema);
module.exports = Imagen;